services:
  serge:
    image: ghcr.io/serge-chat/serge:main
    container_name: serge
    restart: unless-stopped
    ports:
      - 8008:8008
    volumes:
      - serge_weights:/usr/src/app/weights
      - serge_datadb:/data/db/

volumes:
  serge_weights:
    driver_opts:
      type: nfs
      device: ":/Docker/serge/weights"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  serge_datadb:
    driver_opts:
      type: nfs
      device: ":/Docker/serge/datadb"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
